CREATE STREAM car_specs (
    id INTEGER KEY,
    model VARCHAR,
    serie VARCHAR,
    company VARCHAR,
    body_style VARCHAR,
    segment VARCHAR,
    production_years ARRAY<INTEGER>,
    cylinders VARCHAR,
    displacement VARCHAR,
    power_hp VARCHAR,
    power_bhp VARCHAR,
    power_kw VARCHAR,
    torque_lb_ft VARCHAR,
    torque_nm VARCHAR,
    electrical_motor_power VARCHAR,
    electrical_motor_torque VARCHAR,
    fuel_system VARCHAR,
    fuel VARCHAR,
    fuel_capacity VARCHAR,
    top_speed VARCHAR,
    acceleration_0_62 VARCHAR,
    drive_type VARCHAR,
    gearbox VARCHAR,
    front_brake VARCHAR,
    rear_brake VARCHAR,
    tire_size VARCHAR,
    car_length VARCHAR,
    car_width VARCHAR,
    car_height VARCHAR,
    front_rear_track VARCHAR,
    wheelbase VARCHAR,
    ground_clearance VARCHAR,
    aerodynamics_cd VARCHAR,
    aerodynamics_frontal_area VARCHAR,
    turning_circle VARCHAR,
    cargo_volume VARCHAR,
    unladen_weight VARCHAR,
    gross_weight_limit VARCHAR,
    combined_mpg VARCHAR,
    city_mpg VARCHAR,
    highway_mpg VARCHAR,
    co2_emissions VARCHAR,
    co2_emissions_combined VARCHAR,
    turning_circle_curb_to_curb VARCHAR,
    total_max_power VARCHAR,
    power_pack VARCHAR,
    nominal_capacity VARCHAR,
    top_speed_electrical VARCHAR,
    ev_range VARCHAR,
    high_mpg VARCHAR,
    extra_high_mpg VARCHAR,
    medium_mpg VARCHAR,
    low_mpg VARCHAR,
    total_max_torque VARCHAR,
    max_capacity VARCHAR,
    spec_summary VARCHAR
)
WITH 
(
    kafka_topic='car_specs',
    value_format='json',
    partitions=4
);
