-- database name: ny_motor_vehicle_db
-- owner: airflow

CREATE TABLE ny_motor_vehicle (
    CRASH_DATE DATE,
    CRASH_TIME TIME,
    BOROUGH VARCHAR,
    ZIP_CODE VARCHAR,
    LATITUDE FLOAT,
    LONGITUDE FLOAT,
    COLLISION_LOCATION VARCHAR,
    ON_STREET_NAME VARCHAR,
    CROSS_STREET_NAME VARCHAR,
    OFF_STREET_NAME VARCHAR,
    NUMBER_OF_PERSONS_INJURED INTEGER,
    NUMBER_OF_PERSONS_KILLED INTEGER,
    NUMBER_OF_PEDESTRIANS_INJURED INTEGER,
    NUMBER_OF_PEDESTRIANS_KILLED INTEGER,
    NUMBER_OF_CYCLIST_INJURED INTEGER,
    NUMBER_OF_CYCLIST_KILLED INTEGER,
    NUMBER_OF_MOTORIST_INJURED INTEGER,
    NUMBER_OF_MOTORIST_KILLED INTEGER,
    CONTRIBUTING_FACTOR_VEHICLE_1 VARCHAR,
    CONTRIBUTING_FACTOR_VEHICLE_2 VARCHAR,
    CONTRIBUTING_FACTOR_VEHICLE_3 VARCHAR,
    CONTRIBUTING_FACTOR_VEHICLE_4 VARCHAR,
    CONTRIBUTING_FACTOR_VEHICLE_5 VARCHAR,
    COLLISION_ID INTEGER,
    VEHICLE_TYPE_CODE_1 VARCHAR,
    VEHICLE_TYPE_CODE_2 VARCHAR,
    VEHICLE_TYPE_CODE_3 VARCHAR,
    VEHICLE_TYPE_CODE_4 VARCHAR,
    VEHICLE_TYPE_CODE_5 VARCHAR
);

COPY ny_motor_vehicle(
    CRASH_DATE,
    CRASH_TIME,
    BOROUGH,
    ZIP_CODE,
    LATITUDE,
    LONGITUDE,
    COLLISION_LOCATION,
    ON_STREET_NAME,
    CROSS_STREET_NAME,
    OFF_STREET_NAME,
    NUMBER_OF_PERSONS_INJURED,
    NUMBER_OF_PERSONS_KILLED,
    NUMBER_OF_PEDESTRIANS_INJURED,
    NUMBER_OF_PEDESTRIANS_KILLED,
    NUMBER_OF_CYCLIST_INJURED,
    NUMBER_OF_CYCLIST_KILLED,
    NUMBER_OF_MOTORIST_INJURED,
    NUMBER_OF_MOTORIST_KILLED,
    CONTRIBUTING_FACTOR_VEHICLE_1,
    CONTRIBUTING_FACTOR_VEHICLE_2,
    CONTRIBUTING_FACTOR_VEHICLE_3,
    CONTRIBUTING_FACTOR_VEHICLE_4,
    CONTRIBUTING_FACTOR_VEHICLE_5,
    COLLISION_ID,
    VEHICLE_TYPE_CODE_1,
    VEHICLE_TYPE_CODE_2,
    VEHICLE_TYPE_CODE_3,
    VEHICLE_TYPE_CODE_4,
    VEHICLE_TYPE_CODE_5
    )
FROM '/Users/briandunn/Desktop/Projects 2/New York Motor Vehicle Collisions/Motor_Vehicle_Collisions.csv'
DELIMITER ','
CSV HEADER;