\c ctcpd_db_pg;

CREATE TABLE ctcpd_table_pg (
	crash_record_id VARCHAR,
	crash_date_estimate VARCHAR,
	crash_date VARCHAR,
	posted_speed_limit INTEGER,
	traffic_control_device VARCHAR,
	device_condition VARCHAR,
	weather_condition VARCHAR,
	lighting_condition VARCHAR,
	first_crash_type VARCHAR,
	trafficway_type VARCHAR,
	lane_count INTEGER,
	alignment VARCHAR,
	roadway_surface_condition VARCHAR,
	road_defect VARCHAR,
	report_type VARCHAR,
	crash_type VARCHAR,
	intersection_related VARCHAR,
	not_right_of_way VARCHAR,
	hit_and_run VARCHAR,
	damage VARCHAR,
	date_police_notified VARCHAR,
	primary_contributory_cause VARCHAR,
	secondary_contributory_cause VARCHAR,
	street_no INTEGER,
	street_direction VARCHAR,
	street_name VARCHAR,
	beat_of_occurrence INTEGER,
	photos_taken VARCHAR,
	statements_taken VARCHAR,
	dooring VARCHAR,
	work_zone VARCHAR,
	work_zone_type VARCHAR,
	workers_present VARCHAR,
	num_units INTEGER,
	most_severe_injury VARCHAR,
	injuries_total INTEGER,
	injuries_fatal INTEGER,
	injuries_incapacitating INTEGER,
	injuries_non_incapacitating INTEGER,
	injuries_reported_not_evident INTEGER,
	injuries_no_indication INTEGER,
	injuries_unknown INTEGER,
	crash_hour INTEGER,
	crash_day_of_week INTEGER,
	crash_month INTEGER,
	latitude FLOAT,
	longitude FLOAT,
	crash_location VARCHAR
);

COPY ctcpd_table_pg (
	crash_record_id,
	crash_date_estimate,
	crash_date,
	posted_speed_limit,
	traffic_control_device,
	device_condition,
	weather_condition,
	lighting_condition,
	first_crash_type,
	trafficway_type,
	lane_count,
	alignment,
	roadway_surface_condition,
	road_defect,
	report_type,
	crash_type,
	intersection_related,
	not_right_of_way,
	hit_and_run,
	damage,
	date_police_notified,
	primary_contributory_cause,
	secondary_contributory_cause,
	street_no,
	street_direction,
	street_name,
	beat_of_occurrence,
	photos_taken,
	statements_taken,
	dooring,
	work_zone,
	work_zone_type,
	workers_present,
	num_units,
	most_severe_injury,
	injuries_total,
	injuries_fatal,
	injuries_incapacitating,
	injuries_non_incapacitating,
	injuries_reported_not_evident,
	injuries_no_indication,
	injuries_unknown,
	crash_hour,
	crash_day_of_week,
	crash_month,
	latitude,
	longitude,
	crash_location
)
FROM '/docker-entrypoint-initdb.d/data.csv'
DELIMITER ','
CSV HEADER;

ALTER TABLE ctcpd_table_pg
ADD COLUMN id INTEGER GENERATED ALWAYS AS IDENTITY;