\c brazilian_ecomm_public_dataset_pg_db;

DROP TABLE IF EXISTS main_bepd_pg_table;
DROP TABLE IF EXISTS geo_bepd_pg_table;

CREATE TABLE IF NOT EXISTS main_bepd_pg_table (
    OrderStatus VARCHAR,
    OrderPurchaseTimestamp VARCHAR,
    OrderApprovedAt TIMESTAMP,
    OrderDeliveredCarrierDate TIMESTAMP,
    OrderDeliveredCustomerDate TIMESTAMP,
    OrderEstimatedDeliveryDate TIMESTAMP,
    OrderApprovedAt_DayOfWeek INTEGER,
    OrderApprovedAt_DayOfMonth INTEGER,
    OrderApprovedAt_DayOfYear INTEGER,
    OrderApprovedAt_Month INTEGER,
    OrderApprovedAt_Quarter INTEGER,
    OrderApprovedAt_Year INTEGER,
    OrderDeliveredCarrierDate_DayOfWeek INTEGER,
    OrderDeliveredCarrierDate_DayOfMonth INTEGER,
    OrderDeliveredCarrierDate_DayOfYear INTEGER,
    OrderDeliveredCarrierDate_Month INTEGER,
    OrderDeliveredCarrierDate_Quarter INTEGER,
    OrderDeliveredCarrierDate_Year INTEGER,
    OrderDeliveredCustomerDate_DayOfWeek INTEGER,
    OrderDeliveredCustomerDate_DayOfMonth INTEGER,
    OrderDeliveredCustomerDate_DayOfYear INTEGER,
    OrderDeliveredCustomerDate_Month INTEGER,
    OrderDeliveredCustomerDate_Quarter INTEGER,
    OrderDeliveredCustomerDate_Year INTEGER,
    OrderEstimatedDeliveryDate_DayOfWeek INTEGER,
    OrderEstimatedDeliveryDate_DayOfMonth INTEGER,
    OrderEstimatedDeliveryDate_DayOfYear INTEGER,
    OrderEstimatedDeliveryDate_Month INTEGER,
    OrderEstimatedDeliveryDate_Quarter INTEGER,
    OrderEstimatedDeliveryDate_Year INTEGER,
    CarrierDeliveryTurnaroundInMinutes DOUBLE,
    CustomerZipCodePrefix VARCHAR,
    ShippingLimitDate TIMESTAMP,
    OrderItemPrice DOUBLE,
    FreightValue DOUBLE,
    ShippingLimitDate_DayOfWeek INTEGER,
    ShippingLimitDate_DayOfMonth INTEGER,
    ShippingLimitDate_DayOfYear INTEGER,
    ShippingLimitDate_Month INTEGER,
    ShippingLimitDate_Quarter INTEGER,
    ShippingLimitDate_Year INTEGER,
    PaymentSequential INTEGER,
    PaymentType VARCHAR,
    PaymentInstallments BIGINT,
    PaymentValue DOUBLE,
    ReviewScore INTEGER,
    ReviewCommentTitle VARCHAR,
    ReviewCommentMessage VARCHAR,
    ReviewCreationDate TIMESTAMP,
    ReviewAnswerTimestamp TIMESTAMP,
    ReviewCreationDate_DayOfWeek INTEGER,
    ReviewCreationDate_DayOfMonth INTEGER,
    ReviewCreationDate_DayOfYear INTEGER,
    ReviewCreationDate_Month INTEGER,
    ReviewCreationDate_Quarter INTEGER,
    ReviewCreationDate_Year INTEGER,
    ReviewAnswerTimestamp_DayOfWeek INTEGER,
    ReviewAnswerTimestamp_DayOfMonth INTEGER,
    ReviewAnswerTimestamp_DayOfYear INTEGER,
    ReviewAnswerTimestamp_Month INTEGER,
    ReviewAnswerTimestamp_Quarter INTEGER,
    ReviewAnswerTimestamp_Year INTEGER, 
    ProductPhotosQty INTEGER, 
    ProductWeightG INTEGER,
    ProductLengthCm INTEGER,
    ProductHeightCm INTEGER, 
    ProductWidthCm INTEGER, 
    ProductCategoryNameInEnglish VARCHAR
);

CREATE TABLE IF NOT EXISTS geo_bepd_pg_table (
    GeoZipCodePrefix VARCHAR,
    GeometryPoint GEOMETRY(POINT, 4326),
    GeoCity VARCHAR,
    GeoState VARCHAR
);