GRANT INSERT, UPDATE, DELETE, SELECT, CREATE ON ctcpd_db_mysql.* TO 'mysql'@'%';
FLUSH PRIVILEGES;

USE ctcpd_db_mysql;

CREATE TABLE IF NOT EXISTS ctcpd_table_mysql (
    id INT PRIMARY KEY,
	crash_date_estimate INT,
	crash_date VARCHAR(30),
	day_of_month_crash_date INT,
    month_crash_date INT,
    quarter_crash_date INT,
    year_crash_date INT,
    day_of_week_crash_date INT,
    week_of_year_crash_date INT,
    day_of_year_crash_date INT,
	posted_speed_limit INT,
	traffic_control_device INT,
	device_condition INT,
	weather_condition INT,
	lighting_condition INT,
	first_crash_type INT,
	trafficway_type INT,
	lane_count INT,
	alignment INT,
	roadway_surface_condition INT,
	road_defect INT,
	report_type INT,
	crash_type INT,
	intersection_related INT,
	not_right_of_way INT,
	hit_and_run INT,
	damage INT,
	date_police_notified VARCHAR(30),
	day_of_month_police_notified INT,
    month_police_notified INT,
    quarter_police_notified INT,
    year_police_notified INT,
    day_of_week_police_notified INT,
    week_of_year_police_notified INT,
    day_of_year_police_notified INT,
	days_to_report INT,
	primary_contributory_cause VARCHAR(85),
	secondary_contributory_cause VARCHAR(85),
	street_no INT,
	street_direction INT,
	street_name VARCHAR(35),
	beat_of_occurrence INT,
	photos_taken INT,
	statements_taken INT,
	dooring INT,
	work_zone INT,
	work_zone_type INT,
	workers_present INT,
	num_units INT,
	most_severe_injury INT,
	injuries_total INT,
	injuries_fatal INT,
	injuries_incapacitating INT,
	injuries_non_incapacitating INT,
	injuries_reported_not_evident INT,
	injuries_no_indication INT,
	latitude FLOAT,
	longitude FLOAT
);