services:
  postgres:
    image: postgres:14
    container_name: postgres
    hostname: postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
      - pg_data:/var/lib/postgresql/data
    networks:
      - heart_attack_risk_network
    environment:
      - POSTGRES_USER=pg
      - POSTGRES_PASSWORD=pg
      - POSTGRES_DB=ha_risk_pg_db
  
  mongo: # target database
    image: mongo:8.0.0-rc11
    hostname: mongodb
    container_name: mongodb
    networks:
      - heart_attack_risk_network
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodb_user
      MONGO_INITDB_ROOT_PASSWORD: mongodb_password
    volumes:
      - mongo_data:/data/db
      - ./mongo:/docker-entrypoint-initdb.d
    command: mongod --bind_ip_all
    # ------------------------------------------------------------
    #   To Check if startup scripts worked as expected:
    #     docker exec -it mongodb mongosh
    #     db.auth("mongodb_user", "mongodb_password")
    #     show dbs
    #     use har_db_mongo
    #     har_mongo_col
    # ------------------------------------------------------------

volumes:
  pg_data:
  mongo_data:

networks:
  heart_attack_risk_network:
    driver: bridge