\c comp_sc_analysis_db_pg;

DROP TABLE IF EXISTS comp_sc_analysis_table_pg;

CREATE TABLE comp_sc_analysis_table_pg (
    id INT PRIMARY KEY,
    order_number VARCHAR,
    sales_channel VARCHAR,
    warehouse_code VARCHAR,
    procured_date VARCHAR,
    procured_date_day_of_month INT,
    procured_date_month_of_year INT,
    procured_date_quarter INT,
    procured_date_year INT,
    procured_date_day_of_week INT,
    procured_date_week_of_year INT,
    order_date VARCHAR,
    order_date_day_of_month INT,
    order_date_month_of_year INT,
    order_date_quarter INT,
    order_date_year INT,
    order_date_day_of_week INT,
    order_date_week_of_year INT,
    ship_date VARCHAR,
    ship_date_day_of_month INT,
    ship_date_month_of_year INT,
    ship_date_quarter INT,
    ship_date_year INT,
    ship_date_day_of_week INT,
    ship_date_week_of_year INT,
    delivery_date VARCHAR,
    delivery_date_day_of_month INT,
    delivery_date_month_of_year INT,
    delivery_date_quarter INT,
    delivery_date_year INT,
    delivery_date_day_of_week INT,
    delivery_date_week_of_year INT,
    sales_team_id INT,
    customer_id INT,
    store_id INT,
    product_id INT,
    order_quantity INT,
    discount_applied FLOAT,
	unit_cost_in_usd FLOAT,
	unit_price_in_usd FLOAT,
	procured_to_delivery_date INT,
    order_to_delivery_date INT,
    order_to_ship_date INT
);