-- database name: heart_disease_db
-- owner: airflow

CREATE TABLE heart_disease_indicators (
	StateName VARCHAR,
    Sex VARCHAR,
    GeneralHealth VARCHAR,
    PhysicalHealthDays FLOAT,
    MentalHealthDays FLOAT,
    LastCheckupTime VARCHAR,
    PhysicalActivities VARCHAR,
    SleepHours FLOAT,
    RemovedTeeth VARCHAR,
    HadHeartAttack VARCHAR,
    HadAngina VARCHAR,
    HadStroke VARCHAR,
    HadAsthma VARCHAR,
    HadSkinCancer VARCHAR,
    HadCOPD VARCHAR,
    HadDepressiveDisorder VARCHAR,
    HadKidneyDisease VARCHAR,
    HadArthritis VARCHAR,
    HadDiabetes VARCHAR,
    DeafOrHardOfHearing VARCHAR,
    BlindOrVisionDifficulty VARCHAR,
    DifficultyConcentrating VARCHAR,
    DifficultyWalking VARCHAR,
    DifficultyDressingBathing VARCHAR,
    DifficultyErrands VARCHAR,
    SmokerStatus VARCHAR,
    ECigaretteUsage VARCHAR,
    ChestScan VARCHAR,
    RaceEthnicityCategory VARCHAR,
    AgeCategory VARCHAR,
    HeightInMeters FLOAT,
    WeightInKilograms FLOAT,
    BMI FLOAT,
    AlcoholDrinkers VARCHAR,
    HIVTesting VARCHAR,
    FluVaxLast12 VARCHAR,
    PneumoVaxEver VARCHAR,
    TetanusLast10Tdap VARCHAR,
    HighRiskLastYear VARCHAR,
    CovidPos VARCHAR
);

COPY heart_disease_indicators(
    StateName, 
    Sex, 
    GeneralHealth, 
    PhysicalHealthDays, 
    MentalHealthDays, 
    LastCheckupTime, 
    PhysicalActivities, 
    SleepHours, 
    RemovedTeeth, 
    HadHeartAttack, 
    HadAngina, 
    HadStroke, 
    HadAsthma, 
    HadSkinCancer, 
    HadCOPD, 
    HadDepressiveDisorder, 
    HadKidneyDisease, 
    HadArthritis, 
    HadDiabetes, 
    DeafOrHardOfHearing, 
    BlindOrVisionDifficulty, 
    DifficultyConcentrating, 
    DifficultyWalking, 
    DifficultyDressingBathing, 
    DifficultyErrands, 
    SmokerStatus, 
    ECigaretteUsage, 
    ChestScan, 
    RaceEthnicityCategory, 
    AgeCategory, 
    HeightInMeters, 
    WeightInKilograms, 
    BMI, 
    AlcoholDrinkers, 
    HIVTesting, 
    FluVaxLast12, 
    PneumoVaxEver, 
    TetanusLast10Tdap, 
    HighRiskLastYear, 
    CovidPos
    )
FROM '/Users/briandunn/Desktop/Projects 2/Indicators of Heart Disease/data.csv'
DELIMITER ','
CSV HEADER;