\c dataco_sc_pg_db;

COPY dataco_sc_pg_table (
    transaction_type,
    actual_days_to_ship,
    scheduled_days_to_ship,
    benefit_per_order,
    sales_per_customer,
    delivery_status,
    late_delivery_risk,
    category_id,
    category_name,
    customer_city,
    customer_country,
    customer_email,
    customer_fname,
    customer_id,
    customer_lname,
    customer_password,
    customer_segment,
    customer_state,
    customer_street,
    customer_zipcode,
    department_id,
    department_name,
    latitude,
    longitude,
    market,
    order_city,
    order_country,
    order_customer_id,
    order_date,
    order_id,
    order_item_cardprod_id,
    order_item_discount,
    order_item_discount_rate,
    order_item_id,
    order_item_product_price,
    order_item_profit_ratio,
    order_item_quantity,
    sales,
    order_item_total,
    order_profit_per_order,
    order_region,
    order_state,
    order_status,
    order_zipcode,
    product_card_id,
    product_category_id,
    product_desc,
    product_image,
    product_name,
    product_price,
    product_status,
    shipping_date,
    shipping_mode
)
FROM '/data/data.csv'
DELIMITER ','
CSV HEADER;