-- database name: allegheny_db
-- owner: airflow

CREATE TABLE allegheny (
    PARID VARCHAR,
    PROPERTYHOUSENUM INTEGER,
    PROPERTYFRACTION VARCHAR,
    PROPERTYADDRESSDIR VARCHAR,
    PROPERTYADDRESSSTREET VARCHAR,
    PROPERTYADDRESSSUF VARCHAR,
    PROPERTYADDRESSUNITDESC VARCHAR,
    PROPERTYUNITNO VARCHAR,
    PROPERTYCITY VARCHAR,
    PROPERTYSTATE VARCHAR,
    PROPERTYZIP INTEGER,
    SCHOOLCODE INTEGER,
    SCHOOLDESC VARCHAR,
    MUNICODE INTEGER,
    MUNIDESC VARCHAR,
    RECORDDATE DATE, -- looks like normal date
    SALEDATE DATE, -- looks like normal date
    PRICE INTEGER,
    DEEDBOOK VARCHAR,
    DEEDPAGE VARCHAR,
    SALECODE VARCHAR,
    SALEDESC VARCHAR,
    INSTRTYP VARCHAR,
    INSTRTYPDESC VARCHAR
);

COPY allegheny(
    PARID,
    PROPERTYHOUSENUM,
    PROPERTYFRACTION,
    PROPERTYADDRESSDIR,
    PROPERTYADDRESSSTREET,
    PROPERTYADDRESSSUF,
    PROPERTYADDRESSUNITDESC,
    PROPERTYUNITNO,
    PROPERTYCITY,
    PROPERTYSTATE,
    PROPERTYZIP,
    SCHOOLCODE,
    SCHOOLDESC,
    MUNICODE,
    MUNIDESC,
    RECORDDATE,
    SALEDATE,
    PRICE,
    DEEDBOOK,
    DEEDPAGE,
    SALECODE,
    SALEDESC,
    INSTRTYP,
    INSTRTYPDESC
    )
FROM '/Users/briandunn/Desktop/Projects/Allegheny Co Property Sale Transactions/PropertySaleTransactions.csv'
DELIMITER ','
CSV HEADER;