-- database name: ppp_via_foia_db
-- owner: airflow

CREATE TABLE ppp_via_foia (
    LoanNumber BIGINT,
    DateApproved DATE,
    SBAOfficeCode INTEGER,
    ProcessingMethod VARCHAR,
    BorrowerName VARCHAR,
    BorrowerAddress VARCHAR,
    BorrowerCity VARCHAR,
    BorrowerState VARCHAR,
    BorrowerZip VARCHAR,
    LoanStatusDate DATE,
    LoanStatus VARCHAR,
    Term INTEGER,
    SBAGuarantyPercentage INTEGER,
    InitialApprovalAmount FLOAT,
    CurrentApprovalAmount FLOAT,
    UndisbursedAmount FLOAT,
    FranchiseName VARCHAR,
    ServicingLenderLocationID INTEGER,
    ServicingLenderName VARCHAR,
    ServicingLenderAddress VARCHAR,
    ServicingLenderCity VARCHAR,
    ServicingLenderState VARCHAR,
    ServicingLenderZip VARCHAR,
    RuralUrbanIndicator VARCHAR,
    HubzoneIndicator VARCHAR,
    LMIIndicator VARCHAR,
    BusinessAgeDescription VARCHAR,
    ProjectCity VARCHAR,
    ProjectCountyName VARCHAR,
    ProjectState VARCHAR,
    ProjectZip VARCHAR,
    CD VARCHAR,
    JobsReported INTEGER,
    NAICSCode INTEGER,
    Race VARCHAR,
    Ethnicity VARCHAR,
    UTILITIES_PROCEED FLOAT,
    PAYROLL_PROCEED FLOAT,
    MORTGAGE_INTEREST_PROCEED FLOAT,
    RENT_PROCEED FLOAT,
    REFINANCE_EIDL_PROCEED FLOAT,
    HEALTH_CARE_PROCEED FLOAT,
    DEBT_INTEREST_PROCEED FLOAT,
    BusinessType VARCHAR,
    OriginatingLenderLocationID INTEGER,
    OriginatingLender VARCHAR,
    OriginatingLenderCity VARCHAR,
    OriginatingLenderState VARCHAR,
    Gender VARCHAR,
    Veteran VARCHAR,
    NonProfit VARCHAR,
    ForgivenessAmount FLOAT,
    ForgivenessDate DATE
);

COPY ppp_via_foia(
    LoanNumber,
    DateApproved,
    SBAOfficeCode,
    ProcessingMethod,
    BorrowerName,
    BorrowerAddress,
    BorrowerCity,
    BorrowerState,
    BorrowerZip,
    LoanStatusDate,
    LoanStatus,
    Term,
    SBAGuarantyPercentage,
    InitialApprovalAmount,
    CurrentApprovalAmount,
    UndisbursedAmount,
    FranchiseName,
    ServicingLenderLocationID,
    ServicingLenderName,
    ServicingLenderAddress,
    ServicingLenderCity,
    ServicingLenderState,
    ServicingLenderZip,
    RuralUrbanIndicator,
    HubzoneIndicator,
    LMIIndicator,
    BusinessAgeDescription,
    ProjectCity,
    ProjectCountyName,
    ProjectState,
    ProjectZip,
    CD,
    JobsReported,
    NAICSCode,
    Race,
    Ethnicity,
    UTILITIES_PROCEED,
    PAYROLL_PROCEED,
    MORTGAGE_INTEREST_PROCEED,
    RENT_PROCEED,
    REFINANCE_EIDL_PROCEED,
    HEALTH_CARE_PROCEED,
    DEBT_INTEREST_PROCEED,
    BusinessType,
    OriginatingLenderLocationID,
    OriginatingLender,
    OriginatingLenderCity,
    OriginatingLenderState,
    Gender,
    Veteran,
    NonProfit,
    ForgivenessAmount,
    ForgivenessDate
    )
FROM '/Users/briandunn/Desktop/Projects 2/PPP via FOIA/data.csv'
DELIMITER ','
CSV HEADER;