-- database name: ao_db
-- owner: airflow

CREATE TABLE ao (
    ID INTEGER,
    AGE VARCHAR,
    GENDER VARCHAR,
    DRIVING_EXPERIENCE VARCHAR,
    EDUCATION VARCHAR,
    INCOME VARCHAR,
    CREDIT_SCORE FLOAT,
    VEHICLE_OWNERSHIP FLOAT,
    VEHICLE_YEAR VARCHAR,
    MARRIED FLOAT,
    CHILDREN FLOAT,
    POSTAL_CODE INTEGER,
    ANNUAL_MILEAGE FLOAT,
    SPEEDING_VIOLATIONS INTEGER,
    DUIS INTEGER,
    PAST_ACCIDENTS INTEGER,
    OUTCOME FLOAT,
    TYPE_OF_VEHICLE VARCHAR
);

COPY ao(
    ID,
    AGE,
    GENDER,
    DRIVING_EXPERIENCE,
    EDUCATION,
    INCOME,
    CREDIT_SCORE,
    VEHICLE_OWNERSHIP,
    VEHICLE_YEAR,
    MARRIED,
    CHILDREN,
    POSTAL_CODE,
    ANNUAL_MILEAGE,
    SPEEDING_VIOLATIONS,
    DUIS,
    PAST_ACCIDENTS,
    OUTCOME,
    TYPE_OF_VEHICLE
    )
FROM '/Users/briandunn/Desktop/Projects 2/Analytics Olympiad 2022/train.csv'
DELIMITER ','
CSV HEADER;