CREATE TABLE iowa_liquor_sales (
    record_number INTEGER,
    invoice_item_number VARCHAR,
    date_of_sale DATE,
    store_number INTEGER,
    store_name VARCHAR,
    store_address VARCHAR,
    store_city VARCHAR,
    store_zip_code VARCHAR,
    store_location VARCHAR,
    store_county_number VARCHAR,
    store_county VARCHAR,
    item_category VARCHAR,
    category_name VARCHAR,
    vendor_number VARCHAR,
    vendor_name VARCHAR,
    item_number VARCHAR,
    item_description VARCHAR,
    pack INTEGER,
    bottle_volume VARCHAR,
    state_bottle_cost VARCHAR,
    state_bottle_retail VARCHAR,
    bottles_sold VARCHAR,
    sale_dollars VARCHAR,
    volume_sold_liters VARCHAR,
    volume_sold_gallons VARCHAR,
    iowa_zip_code_tabulation_areas VARCHAR,
    iowa_watershed_sub_basins VARCHAR,
    iowa_watersheds VARCHAR,
    county_boundaries_of_iowa VARCHAR,
    us_counties VARCHAR
);

COPY iowa_liquor_sales (
    record_number,
	invoice_item_number,
    date_of_sale,
    store_number,
    store_name,
    store_address,
    store_city,
    store_zip_code,
    store_location,
    store_county_number,
    store_county,
    item_category,
    category_name,
    vendor_number,
    vendor_name,
    item_number,
    item_description,
    pack,
    bottle_volume,
    state_bottle_cost,
    state_bottle_retail,
    bottles_sold,
    sale_dollars,
    volume_sold_liters,
    volume_sold_gallons,
    iowa_zip_code_tabulation_areas,
    iowa_watershed_sub_basins,
    iowa_watersheds,
    county_boundaries_of_iowa,
    us_counties
)
FROM '/Users/briandunn/Desktop/dbt Projects/Iowa_Liquor_Sales/data/Updated_Iowa_Liquor_Sales.csv'
DELIMITER ','
CSV HEADER;