\c mock_marketing_pg_db;

CREATE TABLE IF NOT EXISTS mock_marketing_pg_account (
    "CUST_ID" VARCHAR,
    "ACQUISITION_COST" FLOAT,
    "INTERNET_BANKING_INDICATOR" BOOLEAN,
    "DATE_FIRST_ACCOUNT_OPENED" VARCHAR,
    "DATE_LAST_ACCOUNT_OPENED" VARCHAR,
    "PURSUIT" VARCHAR,
    "PRIMARY_ADVISOR_ORGANIZATION_ID" INTEGER,
    "PRIMARY_BRANCH_PROXIMITY" INTEGER,
    "PRIMARY_SPOKEN_LANGUAGE" VARCHAR,
    "PRIMARY_WRITTEN_LANGUAGE" VARCHAR,
    "SATISFACTION_RATING_FROM_SURVEY" VARCHAR,
    "SECONDARY_ADVISOR_ID" INTEGER,
    "SECONDARY_ADVISOR_ORGANIZATION_ID" INTEGER,
    "SPECIAL_TERMS_INDICATOR" BOOLEAN
);

CREATE TABLE IF NOT EXISTS mock_marketing_pg_customer (
    "CUST_ID" VARCHAR,
    "GENDER" VARCHAR,
    "FIRST_NAME" VARCHAR,
    "LAST_NAME" VARCHAR,
    "EMAIL" VARCHAR,
    "SSN" VARCHAR,
    "AGE_RANGE" VARCHAR,
    "ANNUAL_INCOME" VARCHAR,
    "BIRTH_YEAR" INTEGER,
    "CURRENT_EMPLOYMENT_START_DATE" VARCHAR,
    "CUSTOMER_BEHAVIOR" VARCHAR,
    "EDUCATION_LEVEL" VARCHAR,
    "EMPLOYMENT_STATUS" VARCHAR,
    "MARITAL_STATUS" VARCHAR,
    "MONTHLY_NET_INCOME" INTEGER,
    "PROFESSION" VARCHAR,
    "RETIREMENT_AGE" INTEGER,
    "STATUS" VARCHAR,
    "WALLET_SHARE_PERCENTAGE" INTEGER
);

CREATE TABLE IF NOT EXISTS mock_marketing_pg_financials (
    "CUST_ID" VARCHAR,
    "MONTHLY_HOUSING_COST" INTEGER,
    "CONTACT_PREFERENCE" VARCHAR,
    "CREDIT_AUTHORITY_LEVEL" VARCHAR,
    "CREDIT_SCORE" INTEGER,
    "CREDIT_UTILIZATION" FLOAT,
    "DEBT_SERVICE_COVERAGE_RATIO" INTEGER
);

CREATE TABLE IF NOT EXISTS mock_marketing_pg_household (
    "CUST_ID" VARCHAR,
    "HOUSEHOLD_ID" VARCHAR,
    "ADDRESS" VARCHAR,
    "CITY" VARCHAR,
    "COUNTRY" VARCHAR,
    "STATE" VARCHAR,
    "ZIP" VARCHAR,
    "ADDRESS_LAST_CHANGED_DATE" VARCHAR,
    "NUMBER_OF_DEPENDENT_ADULTS" INTEGER,
    "NUMBER_OF_DEPENDENT_CHILDREN" INTEGER,
    "FAMILY_SIZE" INTEGER,
    "HEAD_OF_HOUSEHOLD_INDICATOR" BOOLEAN,
    "HOME_OWNER_INDICATOR" BOOLEAN,
    "URBAN_CODE" VARCHAR,
    "PRIMARY_ADVISOR_ID" INTEGER
);

CREATE TABLE IF NOT EXISTS mock_marketing_pg_marketing (
    "CUST_ID" VARCHAR,
    "ADVERTISING_INDICATOR" BOOLEAN,
    "ATTACHMENT_ALLOWED_INDICATOR" BOOLEAN,
    "PREFERRED_COMMUNICATION_FORM" VARCHAR,
    "IMPORTANCE_LEVEL_CODE" VARCHAR,
    "INFLUENCE_SCORE" INTEGER,
    "MARKET_GROUP" VARCHAR,
    "LOYALTY_RATING_CODE" INTEGER,
    "RECORDED_VOICE_SAMPLE_ID" INTEGER,
    "REFERRALS_VALUE_CODE" VARCHAR,
    "RELATIONSHIP_START_DATE" VARCHAR
);