\c mock_marketing_pg_db;

COPY mock_marketing_pg_account (
    "CUST_ID",
    "ACQUISITION_COST",
    "INTERNET_BANKING_INDICATOR",
    "DATE_FIRST_ACCOUNT_OPENED",
    "DATE_LAST_ACCOUNT_OPENED",
    "PURSUIT",
    "PRIMARY_ADVISOR_ORGANIZATION_ID",
    "PRIMARY_BRANCH_PROXIMITY",
    "PRIMARY_SPOKEN_LANGUAGE",
    "PRIMARY_WRITTEN_LANGUAGE",
    "SATISFACTION_RATING_FROM_SURVEY",
    "SECONDARY_ADVISOR_ID",
    "SECONDARY_ADVISOR_ORGANIZATION_ID",
    "SPECIAL_TERMS_INDICATOR" 
) 
FROM '/data/Account.csv'
DELIMITER ','
CSV HEADER;

COPY mock_marketing_pg_customer (
    "CUST_ID",
    "GENDER",
    "FIRST_NAME",
    "LAST_NAME",
    "EMAIL",
    "SSN",
    "AGE_RANGE",
    "ANNUAL_INCOME",
    "BIRTH_YEAR",
    "CURRENT_EMPLOYMENT_START_DATE",
    "CUSTOMER_BEHAVIOR",
    "EDUCATION_LEVEL",
    "EMPLOYMENT_STATUS",
    "MARITAL_STATUS",
    "MONTHLY_NET_INCOME",
    "PROFESSION",
    "RETIREMENT_AGE",
    "STATUS",
    "WALLET_SHARE_PERCENTAGE" 
) 
FROM '/data/Customer.csv'
DELIMITER ','
CSV HEADER;

COPY mock_marketing_pg_financials (
    "CUST_ID",
    "MONTHLY_HOUSING_COST",
    "CONTACT_PREFERENCE",
    "CREDIT_AUTHORITY_LEVEL",
    "CREDIT_SCORE",
    "CREDIT_UTILIZATION",
    "DEBT_SERVICE_COVERAGE_RATIO" 
) FROM '/data/Financials.csv'
DELIMITER ','
CSV HEADER;

COPY mock_marketing_pg_household (
    "CUST_ID",
    "HOUSEHOLD_ID",
    "ADDRESS",
    "CITY",
    "COUNTRY",
    "STATE",
    "ZIP",
    "ADDRESS_LAST_CHANGED_DATE",
    "NUMBER_OF_DEPENDENT_ADULTS",
    "NUMBER_OF_DEPENDENT_CHILDREN",
    "FAMILY_SIZE",
    "HEAD_OF_HOUSEHOLD_INDICATOR",
    "HOME_OWNER_INDICATOR",
    "URBAN_CODE",
    "PRIMARY_ADVISOR_ID" 
) 
FROM '/data/Household.csv'
DELIMITER ','
CSV HEADER;

COPY mock_marketing_pg_marketing (
    "CUST_ID",
    "ADVERTISING_INDICATOR",
    "ATTACHMENT_ALLOWED_INDICATOR",
    "PREFERRED_COMMUNICATION_FORM",
    "IMPORTANCE_LEVEL_CODE",
    "INFLUENCE_SCORE",
    "MARKET_GROUP",
    "LOYALTY_RATING_CODE",
    "RECORDED_VOICE_SAMPLE_ID",
    "REFERRALS_VALUE_CODE",
    "RELATIONSHIP_START_DATE"
) 
FROM '/data/Marketing.csv'
DELIMITER ','
CSV HEADER;