\c impact_analysis;
INSERT INTO companies (company_id, company_name, company_location, company_type, employees) VALUES (1, 'Adams-Rice', 'Douglastown', 'public', '500-1,000');
INSERT INTO companies (company_id, company_name, company_location, company_type, employees) VALUES (2, 'Olson-Schneider', 'Vaughnbury', 'private', '1-10');
INSERT INTO companies (company_id, company_name, company_location, company_type, employees) VALUES (3, 'Smith, Weber and Spence', 'Francisborough', 'non-profit', '101-500');
INSERT INTO companies (company_id, company_name, company_location, company_type, employees) VALUES (4, 'Johnston and Sons', 'New Gloriamouth', 'private', '500-1,000');
INSERT INTO companies (company_id, company_name, company_location, company_type, employees) VALUES (5, 'Sullivan, Kirby and Smith', 'Port Robynhaven', 'non-profit', '1-10');
INSERT INTO companies (company_id, company_name, company_location, company_type, employees) VALUES (6, 'Davis Group', 'Rodriguezchester', 'public', '101-500');
INSERT INTO companies (company_id, company_name, company_location, company_type, employees) VALUES (7, 'Ryan PLC', 'Lake Nicole', 'private', '1-10');
INSERT INTO companies (company_id, company_name, company_location, company_type, employees) VALUES (8, 'Jackson, Cabrera and Morales', 'Barnettfort', 'private', '51-100');
INSERT INTO companies (company_id, company_name, company_location, company_type, employees) VALUES (9, 'Lynch-Weaver', 'East Theresaview', 'private', '51-100');
INSERT INTO companies (company_id, company_name, company_location, company_type, employees) VALUES (10, 'Everett-Cline', 'Nunezville', 'private', '51-100');
