-- database name: ca_housing_data_db
-- owner: airflow

CREATE TABLE ca_housing_data (
    id INTEGER,
    index_id INTEGER,
    SALE_TYPE VARCHAR,
    SOLD_DATE DATE,
    PROPERTY_TYPE VARCHAR,
    STREET_ADDRESS VARCHAR,
    CITY VARCHAR,
    STATE_OR_PROVINCE VARCHAR,
    ZIP_OR_POSTAL_CODE VARCHAR,
    PRICE FLOAT,
    BEDS FLOAT,
    BATHS FLOAT,
    PROPERTY_LOCATION VARCHAR,
    SQUARE_FEET FLOAT,
    LOT_SIZE FLOAT,
    YEAR_BUILT FLOAT,
    DAYS_ON_MARKET FLOAT,
    PRICE_PER_SQUARE_FOOT FLOAT,
    HOA_PER_MONTH FLOAT,
    SALES_STATUS VARCHAR,
    NEXT_OPEN_HOUSE_START_TIME TIMESTAMP,
    NEXT_OPEN_HOUSE_END_TIME TIMESTAMP,
    URL_STRING VARCHAR,
    URL_SOURCE VARCHAR,
    MLS VARCHAR,
    FAVORITE VARCHAR,
    INTERESTED VARCHAR,
    LATITUDE FLOAT,
    LONGITUDE FLOAT
);

COPY ca_housing_data(
    id,
    index_id,
    SALE_TYPE,
    SOLD_DATE,
    PROPERTY_TYPE,
    STREET_ADDRESS,
    CITY,
    STATE_OR_PROVINCE,
    ZIP_OR_POSTAL_CODE,
    PRICE,
    BEDS,
    BATHS,
    PROPERTY_LOCATION,
    SQUARE_FEET,
    LOT_SIZE,
    YEAR_BUILT,
    DAYS_ON_MARKET,
    PRICE_PER_SQUARE_FOOT,
    HOA_PER_MONTH,
    SALES_STATUS,
    NEXT_OPEN_HOUSE_START_TIME,
    NEXT_OPEN_HOUSE_END_TIME,
    URL_STRING,
    URL_SOURCE,
    MLS,
    FAVORITE,
    INTERESTED,
    LATITUDE,
    LONGITUDE
    )
FROM '/Users/briandunn/Desktop/Projects/CA Housing Data/CA_housing_data.csv'
DELIMITER ','
CSV HEADER;