services:
  elasticsearch: # Source
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.28
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=es_prefect_pass
      # (Optional) Disable SSL for HTTP for testing purposes:
      - xpack.security.http.ssl.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -fsSL http://localhost:9200/_cluster/health?wait_for_status=yellow&timeout=10s || exit 1"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    networks:
      - project_network

  data-loader:
    build: ./data-loader
    container_name: data-loader
    depends_on:
      elasticsearch:
        condition: service_healthy
    volumes:
      - ./data-loader/data:/data
    networks:
      - project_network
    # Run the index creation script followed by the bulk upload script.
    command: sh -c "python /app/create_index.py && python /app/bulk_loader.py"

  mariadb: # Target
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: csca_mariadb_db
      MYSQL_USER: mariadb_user
      MYSQL_PASSWORD: mariadb_password
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./mariadb_init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - project_network

  database: # Prefect Database
    image: postgres:alpine
    container_name: database
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=prefect
    expose:
      - 5432
    volumes: 
      - db:/var/lib/postgresql/data
    profiles: ["server"]
    networks:
      - project_network

  minio: # MinIO for flow storage
    image: minio/minio:latest
    container_name: minio
    entrypoint: ["minio", "server", "--address", "0.0.0.0:9000", "--console-address", "0.0.0.0:9001", "/data"]
    volumes:
      - "minio:/data"
    ports:
      - 9000:9000
      - 9001:9001
    profiles: ["minio"]
    networks:
      - project_network

  server: # Prefect Server API & UI
    image: prefecthq/prefect:3.0.10-python3.11
    container_name: prefect-server
    restart: always
    volumes:
      - prefect:/root/.prefect
    entrypoint: ["/opt/prefect/entrypoint.sh", "prefect", "server", "start"]
    environment:
      - PREFECT_UI_URL=http://127.0.0.1:4200/api
      - PREFECT_API_URL=http://127.0.0.1:4200/api
      - PREFECT_SERVER_API_HOST=0.0.0.0
      - PREFECT_API_DATABASE_CONNECTION_URL=postgresql+asyncpg://postgres:postgres@database:5432/prefect
    ports:
      - 4200:4200
    depends_on:
      - database
    profiles: ["server"]
    networks:
      - project_network

  ## Prefect Worker
  worker:
    image: prefecthq/prefect:3.0.10-python3.11
    container_name: prefect-worker-1
    restart: always
    entrypoint: ["/opt/prefect/entrypoint.sh", "prefect", "worker", "start", "-p", "COMP_SUPPLY_CHAIN_ANALYSIS_QUEUE"]
    environment:
      - PREFECT_API_URL=http://server:4200/api
    profiles: ["worker"]
    networks:
      - project_network

  prefect-cli: # Prefect CLI Service
    build: .  
    image: prefect-cli:latest
    container_name: prefect-cli
    entrypoint: ["bash", "-c", "tail -f /dev/null"]
    working_dir: "/root/flows"
    volumes:
      - "./flows:/root/flows"
      - "./data:/root/db"
    environment:
      - PREFECT_API_URL=http://server:4200/api
    profiles: ["cli"]
    networks:
      - project_network

volumes:
  es_data:
  mariadb_data:
  prefect:
  db:
  minio:

networks:
  project_network:

# Other helpful statements/commands

# docker compose --profile server up -d
# docker compose --profile worker up -d
# docker compose --profile minio up -d
# docker compose --profile cli up -d


# docker compose up -d --no-deps --force-recreate --build prefect-cli


# docker compose --profile server down -v
# docker compose --profile worker down -v
# docker compose --profile minio down -v
# docker compose --profile cli down -v



# Check that libraries were correctly installed:
# >> docker exec -it prefect-cli bash
# >> pip list