-- database name: insurance_fraud_db
-- owner: airflow

CREATE TABLE insurance_fraud (
    Month_accident VARCHAR,
    WeekOfMonth INTEGER,
    DayOfWeek VARCHAR,
    Make VARCHAR,
    AccidentArea VARCHAR,
    DayOfWeekClaimed VARCHAR,
    MonthClaimed VARCHAR,
    WeekOfMonthClaimed INTEGER,
    Sex VARCHAR,
    MaritalStatus VARCHAR,
    Age INTEGER,
    Fault VARCHAR,
    PolicyType VARCHAR,
    VehicleCategory VARCHAR,
    VehiclePrice VARCHAR,
    FraudFound_P INTEGER,
    PolicyNumber INTEGER,
    RepNumber INTEGER,
    Deductible INTEGER,
    DriverRating INTEGER,
    Days_Policy_Accident VARCHAR,
    Days_Policy_Claim VARCHAR,
    PastNumberOfClaims VARCHAR,
    AgeOfVehicle VARCHAR,
    AgeOfPolicyHolder VARCHAR,
    PoliceReportFiled VARCHAR,
    WitnessPresent VARCHAR,
    AgentType VARCHAR,
    NumberOfSuppliments VARCHAR, 
    AddressChange_Claim VARCHAR,
    NumberOfCars VARCHAR,
    Year_accident INTEGER,
    BasePolicy VARCHAR
);

COPY insurance_fraud(
    Month_accident,
    WeekOfMonth,
    DayOfWeek,
    Make,
    AccidentArea,
    DayOfWeekClaimed,
    MonthClaimed,
    WeekOfMonthClaimed,
    Sex,
    MaritalStatus,
    Age,
    Fault,
    PolicyType,
    VehicleCategory,
    VehiclePrice,
    FraudFound_P,
    PolicyNumber,
    RepNumber,
    Deductible,
    DriverRating,
    Days_Policy_Accident,
    Days_Policy_Claim,
    PastNumberOfClaims,
    AgeOfVehicle,
    AgeOfPolicyHolder,
    PoliceReportFiled,
    WitnessPresent,
    AgentType,
    NumberOfSuppliments,
    AddressChange_Claim,
    NumberOfCars,
    Year_accident,
    BasePolicy
    )
FROM '/Users/briandunn/Desktop/Projects 2/Insurance Fraud/fraud_oracle.csv'
DELIMITER ','
CSV HEADER;