USE us_schools_geo_mysql_db;

-- Create us_schools_geo_mysql_table_private table
DROP TABLE IF EXISTS us_schools_geo_mysql_table_private;
CREATE TABLE us_schools_geo_mysql_table_private (
    X VARCHAR(20),
    Y VARCHAR(20),
    FID VARCHAR(10),
    OBJECTID VARCHAR(10),
    NCESID VARCHAR(18),
    NAME VARCHAR(70),
    ADDRESS VARCHAR(70),
    CITY VARCHAR(35),
    STATE VARCHAR(4),
    ZIP VARCHAR(6),
    ZIP4 VARCHAR(16),
    TELEPHONE VARCHAR(16),
    TYPE VARCHAR(2),
    STATUS VARCHAR(2),
    POPULATION VARCHAR(10),
    COUNTY VARCHAR(25),
    COUNTYFIPS VARCHAR(10),
    COUNTRY VARCHAR(6),
    LATITUDE VARCHAR(22),
    LONGITUDE VARCHAR(22),
    NAICS_CODE VARCHAR(10),
    NAICS_DESC VARCHAR(40),
    SOURCE VARCHAR(90),
    SOURCEDATE VARCHAR(24),
    VAL_METHOD VARCHAR(20),
    VAL_DATE VARCHAR(24),
    WEBSITE VARCHAR(96),
    LEVEL_ VARCHAR(20),
    ENROLLMENT VARCHAR(10),
    START_GRAD VARCHAR(6),
    END_GRADE VARCHAR(6),
    FT_TEACHER VARCHAR(8),
    SHELTER_ID VARCHAR(18)
);

-- Grant SELECT permission to mysql
GRANT SELECT, UPDATE, INSERT ON us_schools_geo_mysql_table_private TO 'mysql'@'%';
FLUSH PRIVILEGES;


-- Create us_schools_geo_mysql_table_public table
DROP TABLE IF EXISTS us_schools_geo_mysql_table_public;
CREATE TABLE us_schools_geo_mysql_table_public (
    X VARCHAR(20),
    Y VARCHAR(20),
    OBJECTID VARCHAR(10),
    NCESID VARCHAR(18),
    NAME VARCHAR(70),
    ADDRESS VARCHAR(70),
    CITY VARCHAR(35),
    STATE VARCHAR(4),
    ZIP VARCHAR(6),
    ZIP4 VARCHAR(16),
    TELEPHONE VARCHAR(16),
    TYPE VARCHAR(2),
    STATUS VARCHAR(2),
    POPULATION VARCHAR(10),
    COUNTY VARCHAR(25),
    COUNTYFIPS VARCHAR(10),
    COUNTRY VARCHAR(6),
    LATITUDE VARCHAR(22),
    LONGITUDE VARCHAR(22),
    NAICS_CODE VARCHAR(10),
    NAICS_DESC VARCHAR(40),
    SOURCE VARCHAR(90),
    SOURCEDATE VARCHAR(24),
    VAL_METHOD VARCHAR(20),
    VAL_DATE VARCHAR(24),
    WEBSITE VARCHAR(96),
    LEVEL_ VARCHAR(20),
    ENROLLMENT VARCHAR(10),
    ST_GRADE VARCHAR(6),
    END_GRADE VARCHAR(6),
    DISTRICTID VARCHAR(12),
    FT_TEACHER VARCHAR(8),
    SHELTER_ID VARCHAR(18)
);

-- Grant SELECT permission to mysql
GRANT SELECT, UPDATE, INSERT ON us_schools_geo_mysql_table_public TO 'mysql'@'%';
FLUSH PRIVILEGES;