-- database name: market_seg_db
-- owner: airflow

CREATE TABLE market_seg (
    CUST_ID VARCHAR,
    BALANCE FLOAT,
    BALANCE_FREQUENCY FLOAT,
    PURCHASES FLOAT,
    ONEOFF_PURCHASES FLOAT,
    INSTALLMENTS_PURCHASES FLOAT,
    CASH_ADVANCE FLOAT,
    PURCHASES_FREQUENCY FLOAT,
    ONEOFF_PURCHASES_FREQUENCY FLOAT,
    PURCHASES_INSTALLMENTS_FREQUENCY FLOAT,
    CASH_ADVANCE_FREQUENCY FLOAT,
    CASH_ADVANCE_TRX INTEGER,
    PURCHASES_TRX INTEGER,
    CREDIT_LIMIT FLOAT,
    PAYMENTS FLOAT,
    MINIMUM_PAYMENTS FLOAT,
    PRC_FULL_PAYMENT FLOAT,
    TENURE INTEGER
);

COPY market_seg(
    CUST_ID,
    BALANCE,
    BALANCE_FREQUENCY,
    PURCHASES,
    ONEOFF_PURCHASES,
    INSTALLMENTS_PURCHASES,
    CASH_ADVANCE,
    PURCHASES_FREQUENCY,
    ONEOFF_PURCHASES_FREQUENCY,
    PURCHASES_INSTALLMENTS_FREQUENCY,
    CASH_ADVANCE_FREQUENCY,
    CASH_ADVANCE_TRX,
    PURCHASES_TRX,
    CREDIT_LIMIT,
    PAYMENTS,
    MINIMUM_PAYMENTS,
    PRC_FULL_PAYMENT,
    TENURE
    )
FROM '/Users/briandunn/Desktop/Projects 2/Market Segmentation in Insurance Unsupervised/Customer Data.csv'
DELIMITER ','
CSV HEADER;